# Generated by Django 4.2.17 on 2025-04-28 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weatherApp', '0003_rename_croprequirement_croprequirementprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('season', models.CharField(max_length=50)),
                ('monthly_data', models.JSONField(default=dict)),
                ('minor_dry_season_temp', models.FloatField(blank=True, null=True)),
                ('minor_dry_season_rainfall', models.FloatField(blank=True, null=True)),
                ('minor_dry_season_humidity', models.FloatField(blank=True, null=True)),
                ('major_rainy_season_temp', models.FloatField(blank=True, null=True)),
                ('major_rainy_season_rainfall', models.FloatField(blank=True, null=True)),
                ('major_rainy_season_humidity', models.FloatField(blank=True, null=True)),
                ('major_dry_season_temp', models.FloatField(blank=True, null=True)),
                ('major_dry_season_rainfall', models.FloatField(blank=True, null=True)),
                ('major_dry_season_humidity', models.FloatField(blank=True, null=True)),
                ('minor_rainy_season_temp', models.FloatField(blank=True, null=True)),
                ('minor_rainy_season_rainfall', models.FloatField(blank=True, null=True)),
                ('minor_rainy_season_humidity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to=settings.AUTH_USER_MODEL)),
                ('related_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_records', to='weatherApp.croprequirementprediction')),
            ],
            options={
                'unique_together': {('district', 'sector', 'date_recorded')},
            },
        ),
    ]
