# Generated by Django 4.2.17 on 2025-08-02 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='delivery_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days for delivery after full payment', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sell',
            name='payment_completed_date',
            field=models.DateTimeField(blank=True, help_text='Date when full payment was completed', null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Set by buyer during purchase'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Calculated delivery date', null=True),
        ),
    ]
