# Generated by Django 4.2.17 on 2025-08-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellsApp', '0002_sell_delivery_days_sell_payment_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
