# Generated by Django 4.2.17 on 2025-07-09 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('harvest', models.FloatField(blank=True, null=True)),
                ('season', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunflower_harvest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('district', 'sector', 'season', 'harvest')},
            },
        ),
    ]
