# Generated by Django 4.2.17 on 2025-04-25 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=100)),
                ('altitude', models.CharField(max_length=50)),
                ('nitrogen_kg_per_ha', models.FloatField()),
                ('phosphorus_kg_per_ha', models.FloatField()),
                ('potassium_kg_per_ha', models.FloatField()),
                ('water_requirement_mm', models.FloatField()),
                ('optimal_ph', models.FloatField(blank=True, null=True)),
                ('row_spacing_cm', models.IntegerField(blank=True, null=True)),
                ('plant_spacing_cm', models.IntegerField(blank=True, null=True)),
                ('planting_depth_cm', models.IntegerField(blank=True, null=True)),
                ('expected_yield_tons_per_ha', models.FloatField(blank=True, null=True)),
                ('seasonal_recommendations', models.JSONField(blank=True, default=list)),
                ('intercropping_recommendation', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('district', 'sector', 'crop', 'season')},
            },
        ),
    ]
