# Generated by Django 4.2.17 on 2025-04-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprequirement',
            name='altitude',
            field=models.CharField(max_length=250),
        ),
    ]
