# Generated by Django 4.2.17 on 2025-08-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer'), ('buyer', 'Buyer'), ('minagri_officer', 'Minagri Officer')], max_length=20),
        ),
    ]
