# Generated by Django 4.2.17 on 2025-07-31 10:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SunflowerHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quality_grade', models.CharField(choices=[('grade_a', 'Grade A (Premium)'), ('grade_b', 'Grade B (Standard)'), ('grade_c', 'Grade C (Basic)')], max_length=20)),
                ('moisture_content', models.DecimalField(decimal_places=2, help_text='Moisture content (%)', max_digits=5)),
                ('oil_content', models.DecimalField(decimal_places=2, help_text='Oil content (%)', max_digits=5)),
                ('district', models.CharField(help_text='District of storage', max_length=100)),
                ('sector', models.CharField(help_text='Sector of storage', max_length=100)),
                ('cell', models.CharField(help_text='Cell of storage', max_length=100)),
                ('village', models.CharField(help_text='Village of storage', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('harvest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stockApp.sunflowerharvest')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('to_district', models.CharField(blank=True, max_length=100, null=True)),
                ('to_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('to_cell', models.CharField(blank=True, max_length=100, null=True)),
                ('to_village', models.CharField(blank=True, max_length=100, null=True)),
                ('from_district', models.CharField(editable=False, max_length=100)),
                ('from_sector', models.CharField(editable=False, max_length=100)),
                ('from_cell', models.CharField(editable=False, max_length=100)),
                ('from_village', models.CharField(editable=False, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stockApp.harveststock')),
            ],
            options={
                'ordering': ['-movement_date'],
            },
        ),
    ]
