# Generated by Django 4.2.17 on 2025-05-27 05:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driverApp', '0009_remove_driver_residence'),
        ('warehouseApp', '0002_category_commodity_warehousecommodity_and_more'),
        ('vehicleApp', '0008_vehicle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Where the package is coming from', max_length=200)),
                ('cost_charged', models.DecimalField(decimal_places=2, help_text='Cost charged for this order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('availability_status', models.CharField(choices=[('waiting', 'Waiting'), ('imported', 'Imported'), ('exported', 'Exported')], default='waiting', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of commodity to be stored', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouseApp.category')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouseApp.commodity')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver', to='driverApp.driver')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='warehouseApp.inventorymovement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='vehicleApp.vehicle')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouseApp.warehouse')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
