# Generated by Django 4.2.17 on 2025-05-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle',
        ),
    ]
