# Generated by Django 4.2.17 on 2025-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_remove_order_driver_remove_order_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the order has been paid for'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number used for payment', max_length=20),
        ),
    ]
