# Generated by Django 4.2.17 on 2025-05-22 09:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_of_measurement', models.CharField(choices=[('kg', 'Kilograms'), ('tons', 'Tons'), ('liters', 'Liters'), ('pieces', 'Pieces'), ('boxes', 'Boxes'), ('pallets', 'Pallets'), ('cubic_meters', 'Cubic Meters')], default='kg', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='warehouseApp.category')),
            ],
            options={
                'verbose_name_plural': 'Commodities',
                'ordering': ['category__name', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.DecimalField(decimal_places=2, help_text='Maximum quantity this warehouse can store for this commodity', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current quantity stored', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_commodities', to='warehouseApp.commodity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_commodities', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_commodities', to='warehouseApp.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Commodity',
                'verbose_name_plural': 'Warehouse Commodities',
                'unique_together': {('warehouse', 'commodity')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL)),
                ('warehouse_commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouseApp.warehousecommodity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='commodities',
            field=models.ManyToManyField(blank=True, through='warehouseApp.WarehouseCommodity', to='warehouseApp.commodity'),
        ),
    ]
